server.port: 8081

logging.level:
    org.springframework.data.r2dbc: DEBUG
    io.r2dbc: DEBUG

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/reactive-app
    username: postgres
    password: 1234
  sql.init.mode : always
