-- insert into users (id, email, name, password) values (1, 'a@a.com', 'a', '123');
-- insert into users (id, email, name, password) values (2, 'b@a.com', 'b', '1234');
-- insert into users (id, email, name, password) values (3, 'c@a.com', 'c', '1234');
--
-- insert into item (id, name, price, stock_quantity, user_id) values (1, 'item-a', 100, 100, 1);
-- insert into item (id, name, price, stock_quantity, user_id) values (2, 'item-b', 200, 200, 2);
